### PR TITLE
Version3 was missing in ListenConf struct

### PR DESCRIPTION
**Pull request by thebigbone**

### CODE REVIEW

**Comment by cretz** [comment]
This was intentionally removed in: https://github.com/cretz/bine/pull/61. If there are docs or code that need to be updated, we should update them.

**Comment by thebigbone** [comment]
I came across an example which was using it. I will check for anymore occurrences in other code or documentation.

**Review by thebigbone — COMMENTED** [review]
Removed all the occurrences of Version3.

**Review by cretz — APPROVED** [review]
Thanks!

**Review by Breezoo38 — APPROVED** [review]

**Pull request merged**
